name: Deploy via Git Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Deploy to gh-pages branch
        run: |
          # Create or switch to gh-pages branch
          git checkout -B gh-pages
          
          # Remove files we don't want in deployment
          rm -rf .github
          rm -f README.md debug.html
          
          # Add all files and commit
          git add .
          git commit -m "Deploy from main branch - $(date)"
          
          # Force push to gh-pages branch
          git push origin gh-pages --force