name: Enterprise GitHub Pages Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Deploy to gh-pages branch
        run: |
          # Configure git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          
          # Create gh-pages branch if it doesn't exist
          git checkout -B gh-pages
          
          # Remove unwanted files for deployment
          rm -rf .github
          rm -f .gitignore
          rm -f README.md
          rm -f debug.html
          rm -f _config.yml.backup
          
          # Ensure required files exist
          if [ ! -f index.html ]; then
            echo "Error: index.html not found"
            exit 1
          fi
          
          # Add all files and commit
          git add .
          git commit -m "Deploy GitHub Pages - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          
          # Push to gh-pages branch
          git push origin gh-pages --force